[build]
target = "aarch64-unknown-linux-gnu"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-himix100-linux-gcc"
runner = "./target-runner.sh"
rustflags = []

[alias]
b = "build --features hi3559av100"
d = "doc --features hi3559av100"
r = "run --features hi3559av100"
t = "test --features hi3559av100"
