[build]
target = "aarch64-unknown-linux-gnu"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-himix100-linux-gcc"
runner = "./target-runner.sh"
rustflags = [
    "-C", "link-arg=-Wl,--allow-multiple-definition"
]

[alias]
b = "build --features hi3559av100 --features static-link"
d = "doc --features hi3559av100 --features static-link"
r = "run --features hi3559av100 --features static-link"
t = "test --features hi3559av100 --features static-link"
